"""create knowledge tables

Revision ID: 6aec1997cc56
Revises: 2fd9755d5381
Create Date: 2026-08-07 21:20:59.597725

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aec1997cc56"
down_revision: str | Sequence[str] | None = "2fd9755d5381"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_entity_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=255), nullable=True),
        sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_sources")),
        sa.UniqueConstraint(
            "organization_id",
            "source_type",
            "source_entity_id",
            name="uq_knowledge_sources_org_type_entity",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_sources_content_hash"),
        "knowledge_sources",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_organization_id"),
        "knowledge_sources",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_sources_organization_project",
        "knowledge_sources",
        ["organization_id", "project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_project_id"),
        "knowledge_sources",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "chunk_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge_sources.id"],
            name=op.f("fk_knowledge_chunks_source_id_knowledge_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "source_id", "chunk_index", name="uq_knowledge_chunks_source_index"
        ),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_content_hash"),
        "knowledge_chunks",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_organization_id"),
        "knowledge_chunks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_organization_project",
        "knowledge_chunks",
        ["organization_id", "project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_project_id"),
        "knowledge_chunks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_source_id"),
        "knowledge_chunks",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_chunks_source_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_project_id"), table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_organization_project", table_name="knowledge_chunks"
    )
    op.drop_index(
        op.f("ix_knowledge_chunks_organization_id"), table_name="knowledge_chunks"
    )
    op.drop_index(
        op.f("ix_knowledge_chunks_content_hash"), table_name="knowledge_chunks"
    )
    op.drop_table("knowledge_chunks")
    op.drop_index(
        op.f("ix_knowledge_sources_project_id"), table_name="knowledge_sources"
    )
    op.drop_index(
        "ix_knowledge_sources_organization_project", table_name="knowledge_sources"
    )
    op.drop_index(
        op.f("ix_knowledge_sources_organization_id"), table_name="knowledge_sources"
    )
    op.drop_index(
        op.f("ix_knowledge_sources_content_hash"), table_name="knowledge_sources"
    )
    op.drop_table("knowledge_sources")
    # ### end Alembic commands ###
